namespace TwitchChatOverlay.UI.Localization;

/// <summary>String tables for the settings UI. Keys are grouped by tab prefix.</summary>
internal static class LocalizedStrings
{
    public static IReadOnlyDictionary<string, string> Russian { get; } = new Dictionary<string, string>
    {
        ["Window_Title"] = "Настройки TwitchChatOverlay",
        ["Tab_Connection"] = "Подключение",
        ["Tab_Overlay"] = "Оверлей",
        ["Tab_Voice"] = "Голос",
        ["Tab_Filters"] = "Фильтры и доступ",
        ["Tab_Queue"] = "Очередь",
        ["Tab_Hotkeys"] = "Горячие клавиши",
        ["Tab_General"] = "Общее",

        ["Conn_ChannelName"] = "Имя канала",
        ["Conn_ChannelHint"] = "Канал, чат которого читаем. Обычно совпадает с вашим логином на Twitch.",
        ["Conn_ClientId"] = "Client ID приложения Twitch",
        ["Conn_ClientIdHint"] = "Создайте приложение в консоли разработчика Twitch (OAuth Redirect URL: http://localhost) и вставьте сюда его Client ID.",
        ["Conn_OpenConsole"] = "Открыть консоль разработчика",
        ["Conn_Login"] = "Войти через Twitch",
        ["Conn_Logout"] = "Выйти",
        ["Conn_Status"] = "Состояние",
        ["Conn_DeviceCodeHint"] = "Введите этот код на открывшейся странице Twitch:",
        ["Conn_CopyCode"] = "Копировать код",
        ["Conn_Account"] = "Аккаунт",
        ["Conn_LoggedIn"] = "Выполнен вход",
        ["Conn_NotLoggedIn"] = "Вход не выполнен",

        ["Ov_Monitor"] = "Монитор",
        ["Ov_Anchor"] = "Угол привязки",
        ["Ov_AnchorHint"] = "Позиция хранится как угол и отступ, поэтому не сбивается при смене разрешения.",
        ["Ov_OffsetX"] = "Отступ по X",
        ["Ov_OffsetY"] = "Отступ по Y",
        ["Ov_CardWidth"] = "Ширина карточки",
        ["Ov_UsernameFontSize"] = "Размер шрифта ника",
        ["Ov_MessageFontSize"] = "Размер шрифта сообщения",
        ["Ov_Font"] = "Шрифт",
        ["Ov_Background"] = "Цвет фона",
        ["Ov_Opacity"] = "Прозрачность фона",
        ["Ov_CornerRadius"] = "Скругление углов",
        ["Ov_Animation"] = "Анимация",
        ["Ov_AnimationDuration"] = "Длительность анимации",
        ["Ov_Tail"] = "Показ после конца речи",
        ["Ov_ShowBadges"] = "Показывать бейджи",
        ["Ov_ShowAvatar"] = "Показывать аватар",
        ["Ov_UseNameColor"] = "Использовать цвет ника из Twitch",
        ["Ov_ShowText"] = "Показывать текст сообщения",
        ["Ov_Preview"] = "Предпросмотр",
        ["Ov_SetupMode"] = "Режим настройки",
        ["Ov_SetupModeHint"] = "Оверлей будет висеть постоянно, и его можно перетащить мышью. Отпустите кнопку мыши — позиция запишется в угол привязки.",
        ["Ov_Appearance"] = "Внешний вид",
        ["Ov_Position"] = "Положение",
        ["Ov_Content"] = "Содержимое карточки",

        ["V_Engine"] = "Движок синтеза",
        ["V_Gender"] = "Пол голоса",
        ["V_Male"] = "Мужской",
        ["V_Female"] = "Женский",
        ["V_Voice"] = "Голос",
        ["V_Rate"] = "Скорость речи",
        ["V_Pitch"] = "Высота тона",
        ["V_Volume"] = "Громкость озвучки",
        ["V_Device"] = "Устройство вывода",
        ["V_Test"] = "Проверить голос",
        ["V_Testing"] = "Воспроизведение…",
        ["V_Template"] = "Шаблон произношения",
        ["V_TemplateHint"] = "Доступные плейсхолдеры: {user} — ник, {message} — текст сообщения.",
        ["V_DontReadName"] = "Не читать ник",
        ["V_Translit"] = "Транслитерация ников",
        ["V_TranslitHint"] = "Латинские ники переводятся в кириллицу — иначе русский голос читает их по буквам.",
        ["V_UniquePerViewer"] = "Уникальный голос на зрителя",
        ["V_Pool"] = "Набор голосов для раздачи",
        ["V_PoolHint"] = "Каждому зрителю голос назначается по хешу его ID — один и тот же человек всегда звучит одинаково.",
        ["V_Pause"] = "Пауза между сообщениями",
        ["V_NoVoices"] = "Голоса для выбранного движка не найдены.",

        ["F_Access"] = "Кто может запускать озвучку",
        ["F_Reward"] = "Название награды за баллы канала",
        ["F_MaxLen"] = "Максимальная длина сообщения",
        ["F_MaxLenHint"] = "Более длинные сообщения обрезаются.",
        ["F_StripLinks"] = "Вырезать ссылки",
        ["F_StripEmotes"] = "Вырезать эмоуты",
        ["F_IgnoreCommands"] = "Игнорировать команды с !",
        ["F_Collapse"] = "Схлопывать повторы символов",
        ["F_WordBlacklist"] = "Чёрный список слов",
        ["F_UserBlacklist"] = "Чёрный список пользователей",
        ["F_BlacklistHint"] = "По одному значению на строку.",
        ["F_Cooldown"] = "Кулдаун на пользователя",
        ["F_Processing"] = "Обработка текста",

        ["Q_MaxSize"] = "Максимум сообщений в очереди",
        ["Q_Overflow"] = "При переполнении",
        ["Q_SkipOld"] = "Пропускать сообщения старше",

        ["H_Hint"] = "Нажмите «Задать» и введите комбинацию. Нужен хотя бы один модификатор (Ctrl, Alt, Shift, Win). Esc — отмена.",
        ["H_Record"] = "Задать",
        ["H_Recording"] = "Нажмите комбинацию…",
        ["H_Clear"] = "Очистить",
        ["H_NotSet"] = "не задано",

        ["G_Autostart"] = "Запускать вместе с Windows",
        ["G_MinimizeToTray"] = "Сворачивать в трей при закрытии",
        ["G_StartMinimized"] = "Запускать свёрнутым",
        ["G_Language"] = "Язык интерфейса",
        ["G_Russian"] = "Русский",
        ["G_English"] = "English",
        ["G_OpenConfig"] = "Открыть папку конфигурации",
        ["G_Reset"] = "Сбросить настройки",
        ["G_ResetConfirm"] = "Сбросить все настройки к значениям по умолчанию? Токен авторизации будет сохранён.",
        ["G_ResetTitle"] = "Сброс настроек",
        ["G_Export"] = "Экспорт настроек",
        ["G_Import"] = "Импорт настроек",
        ["G_ImportTitle"] = "Выберите файл настроек",
        ["G_ImportError"] = "Не удалось прочитать файл настроек",
        ["G_Version"] = "Версия",
        ["G_Repo"] = "Репозиторий проекта",
        ["G_SettingsFile"] = "Файл настроек",
        ["G_Data"] = "Настройки и данные",
        ["G_About"] = "О программе",
        ["G_Author"] = "Автор",

        ["Unit_Px"] = "px",
        ["Unit_Ms"] = "мс",
        ["Unit_Sec"] = "с",
        ["Unit_Percent"] = "%"
    };

    public static IReadOnlyDictionary<string, string> English { get; } = new Dictionary<string, string>
    {
        ["Window_Title"] = "TwitchChatOverlay settings",
        ["Tab_Connection"] = "Connection",
        ["Tab_Overlay"] = "Overlay",
        ["Tab_Voice"] = "Voice",
        ["Tab_Filters"] = "Filters & access",
        ["Tab_Queue"] = "Queue",
        ["Tab_Hotkeys"] = "Hotkeys",
        ["Tab_General"] = "General",

        ["Conn_ChannelName"] = "Channel name",
        ["Conn_ChannelHint"] = "The channel whose chat is read. Usually the same as your Twitch login.",
        ["Conn_ClientId"] = "Twitch application Client ID",
        ["Conn_ClientIdHint"] = "Create an app in the Twitch developer console (OAuth Redirect URL: http://localhost) and paste its Client ID here.",
        ["Conn_OpenConsole"] = "Open developer console",
        ["Conn_Login"] = "Sign in with Twitch",
        ["Conn_Logout"] = "Sign out",
        ["Conn_Status"] = "Status",
        ["Conn_DeviceCodeHint"] = "Enter this code on the Twitch page that just opened:",
        ["Conn_CopyCode"] = "Copy code",
        ["Conn_Account"] = "Account",
        ["Conn_LoggedIn"] = "Signed in",
        ["Conn_NotLoggedIn"] = "Not signed in",

        ["Ov_Monitor"] = "Monitor",
        ["Ov_Anchor"] = "Anchor corner",
        ["Ov_AnchorHint"] = "The position is stored as a corner plus an offset, so it survives resolution changes.",
        ["Ov_OffsetX"] = "Offset X",
        ["Ov_OffsetY"] = "Offset Y",
        ["Ov_CardWidth"] = "Card width",
        ["Ov_UsernameFontSize"] = "Username font size",
        ["Ov_MessageFontSize"] = "Message font size",
        ["Ov_Font"] = "Font",
        ["Ov_Background"] = "Background colour",
        ["Ov_Opacity"] = "Background opacity",
        ["Ov_CornerRadius"] = "Corner radius",
        ["Ov_Animation"] = "Animation",
        ["Ov_AnimationDuration"] = "Animation duration",
        ["Ov_Tail"] = "Keep on screen after speech",
        ["Ov_ShowBadges"] = "Show badges",
        ["Ov_ShowAvatar"] = "Show avatar",
        ["Ov_UseNameColor"] = "Use Twitch name colour",
        ["Ov_ShowText"] = "Show message text",
        ["Ov_Preview"] = "Preview",
        ["Ov_SetupMode"] = "Setup mode",
        ["Ov_SetupModeHint"] = "The overlay stays visible and can be dragged with the mouse. Release the button and the position is written to the anchor.",
        ["Ov_Appearance"] = "Appearance",
        ["Ov_Position"] = "Position",
        ["Ov_Content"] = "Card content",

        ["V_Engine"] = "Speech engine",
        ["V_Gender"] = "Voice gender",
        ["V_Male"] = "Male",
        ["V_Female"] = "Female",
        ["V_Voice"] = "Voice",
        ["V_Rate"] = "Speech rate",
        ["V_Pitch"] = "Pitch",
        ["V_Volume"] = "Speech volume",
        ["V_Device"] = "Output device",
        ["V_Test"] = "Test voice",
        ["V_Testing"] = "Playing…",
        ["V_Template"] = "Pronunciation template",
        ["V_TemplateHint"] = "Placeholders: {user} — nickname, {message} — message text.",
        ["V_DontReadName"] = "Don't read the nickname",
        ["V_Translit"] = "Transliterate nicknames",
        ["V_TranslitHint"] = "Latin nicknames are converted to Cyrillic — otherwise a Russian voice spells them letter by letter.",
        ["V_UniquePerViewer"] = "Unique voice per viewer",
        ["V_Pool"] = "Voice pool for assignment",
        ["V_PoolHint"] = "Each viewer gets a voice by a hash of their ID — the same person always sounds the same.",
        ["V_Pause"] = "Pause between messages",
        ["V_NoVoices"] = "No voices found for the selected engine.",

        ["F_Access"] = "Who can trigger speech",
        ["F_Reward"] = "Channel points reward name",
        ["F_MaxLen"] = "Maximum message length",
        ["F_MaxLenHint"] = "Longer messages are truncated.",
        ["F_StripLinks"] = "Strip links",
        ["F_StripEmotes"] = "Strip emotes",
        ["F_IgnoreCommands"] = "Ignore ! commands",
        ["F_Collapse"] = "Collapse repeated characters",
        ["F_WordBlacklist"] = "Word blacklist",
        ["F_UserBlacklist"] = "User blacklist",
        ["F_BlacklistHint"] = "One entry per line.",
        ["F_Cooldown"] = "Per-user cooldown",
        ["F_Processing"] = "Text processing",

        ["Q_MaxSize"] = "Maximum queued messages",
        ["Q_Overflow"] = "On overflow",
        ["Q_SkipOld"] = "Skip messages older than",

        ["H_Hint"] = "Click \"Record\" and press the combination. At least one modifier is required (Ctrl, Alt, Shift, Win). Esc cancels.",
        ["H_Record"] = "Record",
        ["H_Recording"] = "Press a combination…",
        ["H_Clear"] = "Clear",
        ["H_NotSet"] = "not set",

        ["G_Autostart"] = "Start with Windows",
        ["G_MinimizeToTray"] = "Minimize to tray on close",
        ["G_StartMinimized"] = "Start minimized",
        ["G_Language"] = "Interface language",
        ["G_Russian"] = "Русский",
        ["G_English"] = "English",
        ["G_OpenConfig"] = "Open config folder",
        ["G_Reset"] = "Reset settings",
        ["G_ResetConfirm"] = "Reset all settings to defaults? The authorization token is kept.",
        ["G_ResetTitle"] = "Reset settings",
        ["G_Export"] = "Export settings",
        ["G_Import"] = "Import settings",
        ["G_ImportTitle"] = "Choose a settings file",
        ["G_ImportError"] = "Could not read the settings file",
        ["G_Version"] = "Version",
        ["G_Repo"] = "Project repository",
        ["G_SettingsFile"] = "Settings file",
        ["G_Data"] = "Settings & data",
        ["G_About"] = "About",
        ["G_Author"] = "Author",

        ["Unit_Px"] = "px",
        ["Unit_Ms"] = "ms",
        ["Unit_Sec"] = "s",
        ["Unit_Percent"] = "%"
    };
}
